abstract final class Consts {
  static const cardMarginHorizontal = 16.0;
  static const cardMarginVertical = 8.0;
  static const cardContentPadding = 12.0;
  static const thumbnailSize = 128.0;
  static const cardRadius = 12.0;
  static const listTopPadding = 8.0;
  static const listBottomPadding = 24.0;
  static const metaIconSize = 16.0;
  static const dateChipHorizontalPadding = 10.0;
  static const dateChipVerticalPadding = 4.0;
  static const descriptionMaxLines = 2;
  static const spaceAfterTitle = 8.0;
  static const spaceBetweenDetails = 4.0;
  static const paginationSpinnerPadding = 16.0;
  static const errorIconSize = 48.0;
  static const errorViewPadding = 24.0;
  static const errorRetrySpacing = 16.0;
  static const pageSize = 20;
  static const loadMoreThreshold = 200.0;
}
